m4: gst-error: remove -Wall/-Werror support for Sun Forte
Something is not right with these checks, they sometimes lead
to build failures on OSX/iOS like e.g.
Undefined symbols for architecture i386:
"rrwarn=%all,no%E_EMPTY_DECLARATION,no%E_STATEMENT_NOT_REACHED,no%E_ARGUEMENT_MISMATCH,no%E_MACRO_REDEFINED,no%E_LOOP_NOT_ENTERED_AT_TOP", referenced from:
implicit entry/start for main executable
ld: symbol(s) not found for architecture i386

Let's just remove the -Wall/-Werror support in case
of this compiler which is most likely completely unused
anyway these days. Code will still compile just fine as
before (hopefully), it's just that we don't get extra
warnings.